#!/usr/bin/env bash
# cleanup.sh — undo the demo. Puts the repo back where it started.
#
#   ./demo/cleanup.sh            # show what would happen
#   ./demo/cleanup.sh --apply    # do it
#
# Removes the kind cluster, the apm install output, npm deps, anything the skills
# generated, and any empty Pulumi stacks — then git-restores the demo files the
# skills edited, so crashloop.yaml crashloops again.
#
# Leaves alone: your logins (~/.pulumi, ~/.claude) and the tools post-create.sh
# installed. A stack with live resources is reported, never deleted.
set -uo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$HERE/.." && pwd)"
CLUSTER="${CLUSTER:-devops-ai-skills}"

APPLY=0
case "${1:-}" in
  --apply) APPLY=1 ;;
  -h|--help) sed -n '2,12p' "$0"; exit 0 ;;
  "") ;;
  *) echo "unknown flag: ${1} (see --help)" >&2; exit 2 ;;
esac

[ "$APPLY" -eq 0 ] && printf '\n*** DRY RUN — nothing will change. Add --apply to do it. ***\n'

step(){ printf '\n==> %s\n' "$1"; }
note(){ printf '    %s\n' "$1"; }

rm_path(){
  local p="$1" d="${2:-}"
  [ -e "$p" ] || { note "skip   ${p#$ROOT/} (absent)"; return; }
  local size; size=$(du -sh "$p" 2>/dev/null | cut -f1)
  if [ "$APPLY" -eq 1 ]; then
    rm -rf "$p" && note "removed ${p#$ROOT/}  (${size})${d:+  — $d}"
  else
    note "would remove ${p#$ROOT/}  (${size})${d:+  — $d}"
  fi
}

step "kind cluster '$CLUSTER'"
if ! command -v kind >/dev/null 2>&1; then
  note "skip   kind not installed (run this inside the devcontainer)"
elif kind get clusters 2>/dev/null | grep -qx "$CLUSTER"; then
  if [ "$APPLY" -eq 1 ]; then
    kind delete cluster --name "$CLUSTER" && note "removed cluster '$CLUSTER'"
  else
    note "would delete cluster '$CLUSTER'"
  fi
else
  note "skip   no cluster named '$CLUSTER'"
fi

step "generated by apm install"
rm_path "$ROOT/.claude"      "skills, settings, guardrail hook"
rm_path "$ROOT/apm_modules"  "resolved skill sources"
rm_path "$ROOT/.mcp.json"
rm_path "$ROOT/.lsp.json"
rm_path "$ROOT/AGENTS.md"
rm_path "$ROOT/CLAUDE.md"

step "npm deps"
rm_path "$ROOT/demo/pulumi-ts/node_modules"
rm_path "$ROOT/slides/node_modules"

step "generated by the skills"
rm_path "$ROOT/payments-infra" "golden-path-service output"

step "Pulumi stacks"
if ! command -v pulumi >/dev/null 2>&1; then
  note "skip   pulumi not installed"
else
  found=0
  while IFS= read -r proj; do
    d="$(dirname "$proj")"
    while IFS= read -r line; do
      case "$line" in NAME*|"") continue ;; esac
      name=$(printf '%s' "$line" | awk '{print $1}' | tr -d '*')
      count=$(printf '%s' "$line" | awk '{print $3}')
      found=1
      if [ "$count" != "n/a" ] && [ "$count" != "0" ]; then
        # Real infrastructure. Deleting it is a decision, not a cleanup.
        note "!! '$name' in ${d#$ROOT/} has $count resources — left alone."
        note "   (cd ${d#$ROOT/} && pulumi destroy -s $name)   # 409 hang: pulumi cancel -s $name --yes"
      elif [ "$APPLY" -eq 1 ]; then
        ( cd "$d" && pulumi stack rm "$name" --yes >/dev/null 2>&1 ) \
          && note "removed empty stack '$name' in ${d#$ROOT/}" \
          || note "warn   could not remove stack '$name' in ${d#$ROOT/}"
      else
        note "would remove empty stack '$name' in ${d#$ROOT/}"
      fi
    done < <(cd "$d" && pulumi stack ls 2>/dev/null | grep -v -e '^warning' -e '^ *\$' -e 'pulumi.com/docs/install')
  done < <(find "$ROOT" -name Pulumi.yaml -not -path '*/node_modules/*' 2>/dev/null)
  [ "$found" -eq 0 ] && note "skip   no stacks found"
fi

step "demo files the skills edited"
# Excludes this script, which also lives in demo/ and must not revert itself.
dirty=$(cd "$ROOT" && git diff --name-only -- demo/ ':(exclude)demo/cleanup.sh' 2>/dev/null)
if [ -z "$dirty" ]; then
  note "ok     demo/ is unchanged"
else
  while IFS= read -r f; do
    [ -z "$f" ] && continue
    if [ "$APPLY" -eq 1 ]; then
      ( cd "$ROOT" && git checkout -- "$f" ) && note "restored $f"
    else
      note "would restore $f"
    fi
  done <<< "$dirty"
fi

if [ "$APPLY" -eq 0 ]; then
  printf '\n*** DRY RUN — nothing changed. Run: ./demo/cleanup.sh --apply ***\n\n'
else
  printf '\nBack to a cold start. Rewarm:  demo/prewarm.sh  then  demo/setup-cluster.sh\n\n'
fi
exit 0
